version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test -v -cover -coverprofile cover.out ./...
      - store_artifacts:
          path: ~/cover.out
          destination: cover.out
